import * as _ from "lodash-es";
import { writeFileSync } from 'fs';



const db = {
  users: [
    {
      id: 1,
      name: 'Conner',
      lastName: 'Jones',
      password: 'dog',
      email: 'conner@example.com',
    },
    {
      id: 2,
      name: 'Smith',
      lastName: 'Johnson',
      password: 'dog',
      email: 'smith@example.com',
    },
    {
      id: 3,
      name: 'Richard',
      lastName: 'Edelson',
      password: 'dog',
      email: 'edelson@example.com',
    },
    {
      id: 4,
      name: 'Kurt',
      lastName: 'Kaesche',
      password: 'dog',
      email: 'kaesche@example.com',
    },
    {
      id: 5,
      name: 'Jon',
      lastName: 'Greenleaf',
      password: 'dog',
      email: 'greenleaf@example.com',
    },
    {
      id: 6,
      name: 'Sedgewick',
      lastName: 'Hamilton',
      password: 'dog',
      email: 'sedgewick@example.com',
    },
    {
      name: 'Kelly',
      lastName: 'Ritz',
      password: 'dog',
      id: 8,
      email: 'kurt@example.com',
    },
    {
      name: 'CJ',
      lastName: 'Kim',
      password: 'dog',
      id: 9,
      email: 'ct@example.com',
    },
    {
      name: 'Biggins',
      lastName: 'Johnson',
      email: 'biggins@gmail.com',
      password: 'dog',
      id: 11,
    },
    {
      name: 'Benson',
      lastName: '',
      email: 'benson@gmail.com',
      password: 'dog',
      id: 12,
    },
    {
      name: 'John',
      lastName: 'Smith',
      email: 'john@gmail.com',
      password: 'dog',
      id: 13,
    },
    {
      name: 'Brett',
      lastName: 'Barnham',
      email: 'brett@gmail.com',
      password: 'dog',
      id: 14,
    },
    {
      name: 'Margaret',
      lastName: 'Johnson',
      email: 'mj@gmail.com',
      password: 'pop',
      id: 15,
    },
  ],
  dogs: [
    {
      id: 4,
      vetId: 12,
      sex: 'M',
      name: 'Clement',
      breed: 'poodle',
      birthDate: '12/18/2017',
      weight: 65.4,
      dateVisited: '9/6/2004',
      notes:
        'Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
      ownerName: 'Clement Leek',
      isActive: false,
    },
    {
      id: 5,
      vetId: 1,
      sex: 'M',
      name: 'Saxon',
      breed: 'poodle',
      birthDate: '2023-09-14',
      weight: 13.5,
      dateVisited: '2023-09-06',
      notes: 'Notes amended',
      ownerName: 'Sauveur Petit',
      isActive: false,
    },
    {
      id: 6,
      vetId: 1,
      sex: 'M',
      name: 'Rave',
      breed: 'golden retriever',
      birthDate: '11/8/2021',
      weight: 83.9,
      dateVisited: '3/7/2007',
      notes:
        'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      ownerName: 'Raviv Blumson',
      isActive: false,
    },
    {
      id: 7,
      vetId: 4,
      sex: 'M',
      name: 'Barney',
      breed: 'poodle',
      birthDate: '12/29/2003',
      weight: 22.6,
      dateVisited: '2/8/2005',
      notes:
        'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
      ownerName: 'Barney Seefus',
      isActive: true,
    },
    {
      id: 8,
      vetId: 5,
      sex: 'M',
      name: 'Winn',
      breed: 'poodle',
      birthDate: '8/7/2022',
      weight: 97.4,
      dateVisited: '6/16/2002',
      notes:
        'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula',
      ownerName: 'Winn Janeway',
      isActive: true,
    },
    {
      sex: 'M',
      name: 'Bisby',
      breed: 'Poodle',
      birthDate: '2021-09-29',
      weight: 2,
      dateVisited: '2023-09-27',
      notes: 'This dog was not sick',
      vetId: 3,
      isActive: false,
      id: 16,
      ownerName: 'Rigby Jones',
    },
    {
      sex: 'M',
      name: 'Barney',
      breed: 'Chihuahua',
      birthDate: '2020-12-22',
      weight: 5,
      dateVisited: '2023-10-02',
      notes: '',
      vetId: 3,
      isActive: true,
      id: 17,
      ownerName: 'Simone Smith',
    },
    {
      sex: 'M',
      name: 'Pepper',
      breed: 'Doberman',
      birthDate: '2019-04-25',
      weight: '85',
      dateVisited: '2023-10-02',
      notes: '',
      vetId: 15,
      isActive: true,
      id: 18,
    },
    {
      sex: 'F',
      name: 'Fido',
      breed: 'Poodle',
      birthDate: '2023-09-25',
      weight: 4,
      dateVisited: '2023-10-04',
      notes: 'notes',
      vetId: 13,
      isActive: false,
      id: 19,
      ownerName: 'Rob Roy',
    },
  ],
  conditions: [
    {
      id: 2,
      conditionName: 'Atopy',
      isActive: true,
    },
    {
      id: 3,
      conditionName: 'Osteoarthritis',
      isActive: true,
    },
    {
      id: 4,
      conditionName: 'Pyoderma',
      isActive: true,
    },
    {
      id: 5,
      conditionName: 'Osteochondritis Dissecans',
      isActive: true,
    },
    {
      id: 6,
      conditionName: 'Diabetes Mellitus',
      isActive: true,
    },
    {
      id: 7,
      conditionName: 'Hyperthyroidism',
      isActive: true,
    },
    {
      id: 9,
      conditionName: 'Pancreatitis',
      isActive: true,
    },
    {
      id: 10,
      conditionName: 'Obesity',
      isActive: true,
    },
    {
      id: 11,
      conditionName: 'Fleas',
      isActive: true,
    },
    {
      id: 12,
      conditionName: 'Ticks',
      isActive: true,
    },
    {
      id: 13,
      conditionName: 'Roundworms',
      isActive: true,
    },
    {
      id: 14,
      conditionName: 'Heartworm',
      isActive: true,
    },
    {
      conditionName: 'Bordetella',
      isActive: true,
      id: 15,
    },
    {
      conditionName: 'Kennel Cough',
      isActive: true,
      id: 16,
    },
    {
      conditionName: 'Intestinal Foreign Body',
      isActive: true,
      id: 19,
    },
    {
      conditionName: 'Bloat',
      isActive: true,
      id: 20,
    },
    {
      conditionName: 'Tapeworms',
      isActive: true,
      id: 21,
    },
  ],
  dogsConditions: [
    {
      dogId: 18,
      conditionId: 3,
      id: 10,
    },
    {
      dogId: 19,
      conditionId: 2,
      id: 16,
    },
    {
      dogId: 19,
      conditionId: 3,
      id: 17,
    },
    {
      dogId: 19,
      conditionId: 4,
      id: 18,
    },
    {
      dogId: 19,
      conditionId: 5,
      id: 19,
    },
    {
      dogId: 19,
      conditionId: 6,
      id: 20,
    },
    {
      dogId: 16,
      conditionId: 3,
      id: 21,
    },
    {
      dogId: '17',
      conditionId: 9,
      id: 22,
    },
  ],
};
writeFileSync("db.json", JSON.stringify(db), { encoding: "utf-8" });